### ISSUE TITLE
CODE "DB3.LITE" could not be downloaded using docker image 

### ISSUE THREAD

**Issue by oleksandrz-tt** [ip2location/docker-ip2location-mysql#1]
https://www.ip2location.com/download?token=9DxIg2zyJqSYufjiAbh........&productcode=DB3.LITE 

returns: Page Not Found

**Comment by ip2location-com** [comment]
Please try again. The product code should be "DB3LITE", without a dot.

**Comment by oleksandrz-tt** [comment]
This works, thank you
