### ISSUE TITLE
IPV6 database can't query ipv4 address.

### ISSUE THREAD

**Issue by fregie** [ip2location/docker-ip2location-mysql#2]
I use `CODE=DB4IPV6` to run a docker container,but I can't query ipv4 address.
Ipv4 range is all in `IPv4Comp`.
So How can I query ipv4 and ipv6 in the same container?

**Comment by ip2location-com** [comment]
The current version can only works with one type of IP address. We will add the supports for both database in next release.

**Comment by fregie** [comment]
Can I send a pull request to add the supports for both?

**Comment by ip2location-com** [comment]
We have rolled out an update with both databases supported.
