### ISSUE TITLE
Unable to up container on ip2location/mysql

### ISSUE THREAD

**Issue by amaleena123** [ip2location/docker-ip2location-mysql#3]
Hi,

Recently I have pulled the latest image on ip2location/mysql but after I tried to docker-compose up -d , I got the below error:  

![image](https://user-images.githubusercontent.com/7087855/146154482-e09380b4-14ff-4e00-9e7b-5adf3e4795f5.png)

The image that I have used which occurred the above error:  

![image](https://user-images.githubusercontent.com/7087855/146154696-18f37442-caac-47fe-9117-b2b895157434.png)

My environment is:
- Docker Desktop 4.3.1 (72247)
- WSL: Ubuntu-18.04

The current solution I can do for now is using image ip2location/mysql:1.02. Then the error does not appear.

Kindly assist. Thank you.

**Comment by ip2location-com** [comment]
Please pull the latest version for the fixes.
